### ISSUE TITLE
Bluetooth MAC history cleared every loop -- intended behavior?

### ISSUE THREAD

**Issue by hobobandy** [JosephHewitt/wardriver_rev3#104]
https://github.com/JosephHewitt/wardriver_rev3/blob/707e14942e8f8e1327f9f76de14676ec13fd7913/B/B.ino#L373

Beginner with C and Arduino/ESP, but I was using your code, specifically the BLE stuff, to muck around with an ESP32-S3 and may have found an unintended behavior at the line above.

Wouldn't clearing the history every loop cancel the intent to only save "not seen" addresses? Also, is this line required nowadays? A.ino doesn't clear the mac_history, and after testing, removing that line in B.ino doesn't seem to break the logic. If it is required, moving it to setup() may be what its intended location was?

Cheers!

**Comment by JosephHewitt** [comment]
Nice find. I'm quite sure this is left over from some early debugging; likely this was added to ensure plenty of data was sent from B->A while testing the parsing on the A side.

You are right that it is not needed. This will be removed in a future release.

Thanks for pointing this out.
