### ISSUE TITLE
boards.txt vs docs? 2.0.7 or 2.0.9?

### ISSUE THREAD

**Issue by pejacoby** [JosephHewitt/wardriver_rev3#105]
I noticed the docs show when setting up the IDE to load boards version 2.0.7.  boards.txt in the code shows "esp32:esp32@2.0.9".  Should the docs refer to 2.0.9 as well and should users update their IDE configs?

**Comment by JosephHewitt** [comment]
Hi,

Thanks for mentioning this. The documentation regarding the version numbers is outdated, the numbers listed in `boards.txt` and `libraries.txt` are the correct versions to use. Updating to 2.0.9 in your IDE is recommended.

I will update the documentation.
