### ISSUE TITLE
Special characters not parsed in WiFi configuration

### ISSUE THREAD

**Issue by JosephHewitt** [JosephHewitt/wardriver_rev3#11]
When configuring a WiFi network to connect to or as a fallback network, special characters can cause issues with the parsing.

Specifically, the HTML form uses GET to transfer the values to the wardriver and the URL encoding isn't handled causing the credentials to be misread.

Switching to POST is probably the best solution which is more suited for the task anyway.

**Comment by K1rdro** [comment]
My workaround for this issue was to print the password on the screen when the device boots. I found it added a couple % signs to mine.

**Comment by JosephHewitt** [comment]
Fixed with PR #22

It would still be beneficial to update this code to use POST requests in the future but for now that is not a priority.
