### ISSUE TITLE
Idea: Total wifi captured on LCD

### ISSUE THREAD

**Issue by symph0nic** [JosephHewitt/wardriver_rev3#122]
What it says on the subject - would be cool to see the 'status' of the current session by showing the total number of wifi networks captured on the LCD, rather than (or as well as) the number currently in range. 

Just an enhancement idea...thanks!

**Comment by JosephHewitt** [comment]
Hey,

Thanks for the suggestion, I like the idea. The only caveat is that the wardriver doesn't keep a full list of discovered networks while running (it only keeps the last 512). This means it might start counting some networks more than once if you travel back into an area which you have already been in.

I don't think that is a giant problem though and will work on this in the future.

**Comment by JosephHewitt** [comment]
This is now implemented, and will be included in the next release (likely 1.2.1).

Thanks for the suggestion, and sorry it took so long to implement.
