### ISSUE TITLE
Inconsistent behavior in *,csv files

### ISSUE THREAD

**Issue by grymoire** [JosephHewitt/wardriver_rev3#14]
I've used the device several times and noticed some minor inconsistencies in the csv files.
Most of the lines end with \r\n
However - some of the lines just end with \n. 

Also some of the MAC addresses use lower case letters while others use upper case letters.
This might cause issue with those that analyze or filter the data.

**Comment by JosephHewitt** [comment]
I have reproduced this and found the cause, I will work on this soon. Thank you for the report.
