### ISSUE TITLE
Compilation error on board B

### ISSUE THREAD

**Issue by PythonEatsSQuirreL** [JosephHewitt/wardriver_rev3#165]
I am getting error when trying to upload the B board on BLEScanResults foundDevices = pBLEScan->start(2.2, false);

Error:

Compilation error: conversion from 'BLEScanResults*' to non-scalar type 'BLEScanResults' requested

Any ideas?

**Comment by PythonEatsSQuirreL** [comment]
it throws the error on verifying also so I guess it's not board related

**Comment by JosephHewitt** [comment]
Hi,

The ESP32 board library was recently updated with breaking changes that are not yet supported by this project, only the 2.x branch is supported.

The suggested version is 2.0.12 which you can install from `Tools -> Board -> Boards Manager`.

The 3.x branch will be supported in a future release.

**Comment by PythonEatsSQuirreL** [comment]
Thank you for the incredible fast solution!

It works with the version specified by you.

Cheers mate!
