### ISSUE TITLE
not booting - stuck at connect to wiggle.uk 012719

### ISSUE THREAD

**Issue by PythonEatsSQuirreL** [JosephHewitt/wardriver_rev3#167]
I think I lost the power when booting a functional wardriver and now each time it starts and it get stuck at not booting - stuck at connect to wiggle.uk 12719 and if I want to connect to the wifi with wardriver.uk password it says the password is incorrect

**Comment by PythonEatsSQuirreL** [comment]
solved by factory resetting the esp32 and flash it again

**Comment by JosephHewitt** [comment]
Hi,

Thank you for this report. I was able to reproduce this and have created a fix to prevent this from happening again in #191 which will be included in the next release.
