### ISSUE TITLE
Find Stalkers - a script to identify devices spotted at multiple locations

### ISSUE THREAD

**Issue by grymoire** [JosephHewitt/wardriver_rev3#19]
I added a new shell/awk script that looks at *.csv files and identies MAC addresses seen at multiple locations.
It can identify the MAC address of people you come into contact frequently.

It's in my repository clone
https://github.com/grymoire/wardriver_rev3/tree/main/scripts

**Comment by JosephHewitt** [comment]
Hi,

Thanks for sharing.

Since this is not a bug report or issue I need to close this.

**Comment by grymoire** [comment]
Thanks. I wasn't sure how to share this.
