### ISSUE TITLE
Delete option in the web UI

### ISSUE THREAD

**Issue by K1rdro** [JosephHewitt/wardriver_rev3#21]
Now that mine is boxed up, I really don't want to have to take it apart to clean up the SD card. Having the option to Delete selected records through the web UI would be a great quality of life upgrade.

**Comment by JosephHewitt** [comment]
Thanks for the suggestion, this would be a nice feature to implement.

I think files should be moved into a separate folder (eg, a trash/recycle bin) so that accidentally deleting the wrong file won't be a big deal.

**Comment by JosephHewitt** [comment]
Now implemented with PR #27

I'm still considering changing it to have a confirmation or recycle bin, but right now it just immediately deletes the file.
