### ISSUE TITLE
Program size too large for B module

### ISSUE THREAD

**Issue by bennybo** [JosephHewitt/wardriver_rev3#25]
When compiling for the B module I get this error using the Arduino IDE.

Sketch uses 1480121 bytes (112%) of program storage space. Maximum is 1310720 bytes.
Global variables use 57020 bytes (17%) of dynamic memory, leaving 270660 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board

**Comment by JosephHewitt** [comment]
It sounds like you may have forgotten to change one of the settings in the `Tools` menu. Most likely one of these ones:


- Board: `ESP32 Dev Module`
- Flash Size: `4MB (32Mb)`
- Partition Scheme: `Minimal SPIFFS (1.9MB APP with OTA/190KB SPIFFS)`
