### ISSUE TITLE
Power draw

### ISSUE THREAD

**Issue by evilskaap** [JosephHewitt/wardriver_rev3#3]
Hi,

I'd like to find out if you've measured the power draw on this setup? I'd like to buy a powerbank that would power it for 12 hours along with the other components.

**Comment by JosephHewitt** [comment]
Hi,

I have measured the power consumption with a very basic cheap "USB safety tester" and the average consumption is around 1.9W with all components. I can't guarantee my data is completely accurate though. Based on this, a 6500mAh+ battery should give you 12 or more hours of runtime.

**Comment by MisterFixx** [comment]
I too measured 1.9 - 2.1 W
