### ISSUE TITLE
Change "Portable Wardriver" to "wardriver.uk"

### ISSUE THREAD

**Issue by JosephHewitt** [JosephHewitt/wardriver_rev3#45]
The old working title `Portable Wardriver` still appears at various places throughout the project. This should be changed to `wardriver.uk` in the documentation, source code, and UI.

**Comment by eitan-lich** [comment]
Hi, could i perhaps be assigned to this task?
Thanks

**Comment by JosephHewitt** [comment]
Thank you.

Closed in #48
